### ISSUE TITLE
Plugin overtaking post thumbnail size

### ISSUE THREAD

**Issue by jennafarr** [wp-document-revisions/wp-document-revisions#339] opened 2024-01-23 18:48 UTC
### Describe the bug

When this plugin is installed, it impacts in particular, the WordPress Featured Image block (and more specifically the Cover block using a Featured Image as the image source). We tracked this down to the plugin adding a post-thumbnail image size within wp-document-revisions/includes/class-wp-document-revisions.php

### Steps to reproduce the behavior

1. Install Document Revisions and Activate
2. Using the Site Editor in a block theme, create a template and insert a cover image block to the template and select featured image and the thumbnail source
3. Publish your template and you'll see that the block is loading the 150x150 (or whatever is set as 'thumbnail') to the block. No setting in WordPress currently to change/specify image resolution or source selection

### Expected behavior

We don't actually see a way to override this through filters; adding a size called `post-thumbnail` causes the cover image block to use that size instead of full.

Document revisions itself doesn't appear to use this size on the frontend; perhaps it was added it to handle displaying the media in the admin?

**Comment by NeilWJames** [comment] 2024-01-25 00:26
@jennafarr,
Thank you for raising the issue. I implemented the Featured Image support into Version 3.2 of the plugin.

During  the Development process, the metabox on the Documents admin screen did not render the image properly. That was because the standard WP metabox uses the post-thumbnail image size but the theme did not set one up.

Therefore I added the logic that says "if the theme has not added the post-thumbnail image size, then add one to make the metabox work." So, yes, it was added for the admin screen.

However, it may also be used in the front-end - by the provided blocks if you choose to display the featured image with the document links. This is optional, however.

I has been unable to reproduce your problem  - however this may be associated with the template creation process and my lack of familiarity with the continual block/site editor changes.

If you are convinced that this is the source of the issue, then you can use this code:
```
<?php
/**
Plugin Name: WP Document Revisions - Remove WPDR post_thumbnail
Description: Remove WPDR post_thumbnail (if added).
Version: 1.0
Author: Neil W. James
License: GPL3
 */

	add_action( 'init', 'wpdr_check_post_thumbnail', 9 );
	add_action( 'init', 'wpdr_remove_post_thumbnail', 11 );

function wpdr_check_post_thumbnail() {
	global $wpdr_post_thumbnail;
	$wpdr_post_thumbnail = array_key_exists( 'post-thumbnail', wp_get_additional_image_sizes() );
}
 
function wpdr_remove_post_thumbnail() {
	global $wpdr_post_thumbnail;
	if ( !  $wpdr_post_thumbnail ) {
		remove_image_size( 'post-thumbnail' );
	}
}
```
Put this into a file called `wpdr_post_thumbnail.php`. Then either store the file in `/wp-content/mu-plugins` (if you are familar with this) or create a folder called `wpdr_post_thumbnail` in your plugins directory and put the file into that. With the latter option it will appear in your plugins list - and you can then activate (or deactivate) the code.

What it does is to before the plugin processing to add the image size is run, it stores a value noting if the plugin will create it, then after it has run looks at that value to determine whether the plugin created it and if so deletes it again.

If this code is running the you will see the processing without the image size.

Hope this is of use,
Neil James

**Comment by NeilWJames** [comment] 2024-03-12 20:17
@jennafarr
Thank you for raising this issue.

The WP documentation states that image sizes should normally be set by the theme and before the plugins start. Since this plugin needs the size set, then it will create it using the thumbnail size if it does not already exist. 

I have merged a fix into this code..

This is by adding a filter document_post_thumbnail which acts over the size attributes [width, height, crop]
(with defaults taken from the thumbnail sizes).

Hope this is of use,
Neil James

**Closed by NeilWJames** 2024-03-12 20:17 UTC
